# Generated by Django 3.0.5 on 2020-04-06 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schooluser',
            name='name',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
