# Generated by Django 3.0.5 on 2020-04-06 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20200406_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schooluser',
            name='name',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
