# Generated by Django 3.0.5 on 2020-04-06 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_auto_20200406_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schooluser',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='schooluser',
            name='surname',
            field=models.CharField(default='', max_length=50),
        ),
    ]
