# Generated by Django 3.0.5 on 2020-04-06 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_auto_20200406_1633'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schooluser',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='schooluser',
            old_name='surname',
            new_name='last_name',
        ),
    ]
