from django.conf.urls import url
from django.conf.urls.static import static
from django.urls import path
from sempy import settings
from .views import (
    HomeView,
    SignUpRequestView,
    ThanksView,
    MyGroupsView,
    FileField,
    Checkout,
    change_password,
    GroupDetail,
    add_user_to_group,
    decline_request,
    delete_group,
    edit_group_name,
    ProfileView,
    AllGroupsView,
    LectureCreatorView,
    LecturesListView,
    LectureDetailView,
    HomeTaskCreatorView,
    TaskDetailView,
    TaskListView,
    PostCreator,
    QuestionView,
)

urlpatterns = [
    url(r'^$', HomeView.as_view(), name="home"),
    path('signup/', SignUpRequestView.as_view(), name="signup"),
    path('thanks/', ThanksView.as_view(), name="thanks"),
    path('profile/my_groups', MyGroupsView.as_view(), name="my_groups"),
    path('profile/upload_users/', FileField.as_view(), name="upload"),
    path('profile/upload_users/checkout/', Checkout.as_view(), name="checkout"),
    path('profile/change_password/', change_password, name='change_password'),
    path('profile/<slug:name>_<int:pk>_<int:creator_id>/', GroupDetail.as_view(), name='group_detailed_view'),
    path('profile/add_<int:pk>', add_user_to_group, name='add'),
    path('profile/decline_<int:pk>', decline_request, name='decline'),
    path('profile/delete_<int:pk>/', delete_group, name='delete_group'),
    path('profile/edit_<int:pk>/', edit_group_name, name='edit_group'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile/all_groups/', AllGroupsView.as_view(), name='all_groups'),
    path('profile/create_lecture', LectureCreatorView.as_view(), name='create_lecture'),
    path('profile/all_lectures', LecturesListView.as_view(), name='list_lectures'),
    path('profile/lecture_<int:pk>', LectureDetailView.as_view(), name='lecture'),
    path('profile/create_home_task', HomeTaskCreatorView.as_view(), name='create_home_task'),
    path('profile/all_tasks', TaskListView.as_view(), name='list_tasks'),
    path('profile/task_<int:pk>', TaskDetailView.as_view(), name='task'),
    path('test_post', PostCreator.as_view()),
    path('test_poll', QuestionView.as_view()),
] + static(settings.FILES_URL, document_root=settings.FILES_ROOT)